In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
def load_and_preprocess_data():
  iris =load_iris()
  x = iris.data
  y=iris.target

  scaler = StandardScaler()
  x_scaled = scaler.fit_transform(x)

  return x_scaled,y,iris

x,y,iris = load_and_preprocess_data()

In [ ]:
def split_data(x,y,test_size=0.2,random_state=42):
    return train_test_split(x,y,test_size=test_size,random_state=random_state)
x_train,x_test,y_train,y_test = split_data(x,y)

In [ ]:
def train_knn_model(x_train,y_train,n_neighbors=3):
    knn= KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    return knn
k=3
knn=train_knn_model(x_train,y_train,k)

In [ ]:
def evaluate_model(knn,x_test,y_test):
    y_pred = knn.predict(x_test)
    accuracy = accuracy_score(y_test,y_pred)
    conf_matrix = confusion_matrix(y_test,y_pred)
    class_report = classification_report(y_test,y_pred)
    print(f"Accuracy: {accuracy}")
    print("Confusion Matrix:")
    print(conf_matrix)
    print("Classification Report:")
    print(class_report)
evaluate_model(knn,x_test,y_test)

Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
def perform_cross_validation(x,y,k=3):
  knn=KNeighborsClassifier(n_neighbors=k)
  cv_scores=cross_val_score(knn,x,y,cv=5)
  print(f"\nCross-Validation results for K={k}:")
  print(f"Mean Accuracy: {cv_scores.mean()*100:.2f}%")
  print(f"standard deviation:{cv_scores.std()*100:.2f}%")

perform_cross_validation(x,y,k)


Cross-Validation results for K=3:
Mean Accuracy: 95.33%
standard deviation:3.40%


In [ ]:
def predict_user_input(knn,scaler,iris):
  try:
    sepal_length = float(input("Enter sepal length(cm): "))
    sepal_width = float(input("Enter sepal width(cm): "))
    petal_length = float(input("Enter petal length(cm): "))
    petal_width = float(input("Enter petal width(cm): "))
  except ValueError:
    print("Invalid input.Please enter numerical values")
    return
  user_input = np.array([[sepal_length,sepal_width,petal_length,petal_width]])
  # Create a new StandardScaler instance and fit it on the original data
  scaler = StandardScaler()
  scaler.fit(x) # Fit the scaler to your original data (x)
  user_input_scaled = scaler.transform(user_input) # Then transform user input
  prediction = knn.predict(user_input_scaled)
  species_names = iris.target_names
  predicted_species=species_names[prediction[0]]
  print(f"\nPredicted Species: {predicted_species}")
# Call the function with the fitted scaler
predict_user_input(knn,StandardScaler(),iris)

Enter sepal length(cm): 10
Enter sepal width(cm): 10
Enter petal length(cm): 10
Enter petal width(cm): 10

Predicted Species: virginica
