In [ ]:
print("NAME: B GANESH, ENROLLMENT NUMBER: 2203031240209")
import statistics as st
import numpy as np
import pandas as pd

NAME: B GANESH, ENROLLMENT NUMBER: 2203031240209


In [ ]:
a1 = np.array(20)
print(a1)
print('Dim', a1.ndim)

20
Dim 0


In [ ]:
a2 = np.array([10,20,30, 20, 405, 505, 50, 50])
print(a2)
print('Dim', a2.ndim)

[ 10  20  30  20 405 505  50  50]
Dim 1


In [ ]:
a3 = np.array([[10,20,30],[40,50,60], [505, 50, 50]])
print(a3)
print('Dim', a3.ndim)

[[ 10  20  30]
 [ 40  50  60]
 [505  50  50]]
Dim 2


In [ ]:
a4 = np.array([[[10]]])
print(a4)
print('Dim', a4.ndim)

[[[10]]]
Dim 3


In [ ]:
a3 = np.array([[10,20,30],[40,50,60],[505, 50, 50]], dtype = np.int16)
print(a3)
print('Dim', a3.ndim)
print('Shape', a3.shape)
print('Size', a3.size)
print('Irem Size', a3.itemsize)
print('Data Type', a3.dtype)

[[ 10  20  30]
 [ 40  50  60]
 [505  50  50]]
Dim 2
Shape (3, 3)
Size 9
Irem Size 2
Data Type int16


In [ ]:
a4 = np.array([505, 50, 50, 40])
print('Shape', a4.shape)

Shape (4,)


In [ ]:
a4 = np.array([[[1],[1]], [[1],[1]]])
print('Shape', a4.shape)
print('Size', a4.size)

Shape (2, 2, 1)
Size 4


In [ ]:
a11 = np.empty([5, 5])
a11

array([[ 2.67090534e-316,  0.00000000e+000,  1.57326251e-313,
         7.90292346e-308,  1.27733780e+294],
       [ 3.06084537e-318,  4.03775148e+202,  3.45845952e-323,
         5.97495324e-318,  3.68310565e-309],
       [ 8.63863900e-319,  6.10888108e-307,  0.00000000e+000,
        -1.42873649e-101,  4.94065646e-324],
       [ 1.98856073e+289,  1.98309484e-312,  1.94906280e+289,
         2.31959604e-309,  1.27733780e+294],
       [ 1.01060357e-312,  0.00000000e+000,  0.00000000e+000,
        -3.49699625e-125,  5.66141846e-314]])

In [ ]:
a12 = np.zeros([3, 5])
a12

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a13 = np.ones([4, 4])
a13

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a14 = np.arange(100)
a14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a15 = np.arange(2, 101, 2)
a15

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
a16 = np.reshape(a15, (10, 5))
a16

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [ ]:
a1 = np.arange(10)
a2 = np.arange(11, 21)
print(a1, a2)

[0 1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19 20]


In [ ]:
print (a1+2)
print (a1-2)
print (a1*2)
print (a1/2)
print (a1**2)

[ 2  3  4  5  6  7  8  9 10 11]
[-2 -1  0  1  2  3  4  5  6  7]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
print (a1+a2)
print (a1-a2)
print (a1*a2)
print (a1/a2)
print (a1**a2)

[11 13 15 17 19 21 23 25 27 29]
[-11 -11 -11 -11 -11 -11 -11 -11 -11 -11]
[  0  12  26  42  60  80 102 126 152 180]
[0.         0.08333333 0.15384615 0.21428571 0.26666667 0.3125
 0.35294118 0.38888889 0.42105263 0.45      ]
[                   0                    1                 8192
              4782969           1073741824         152587890625
       16926659444736     1628413597910449   144115188075855872
 -6289078614652622815]


In [ ]:
a1 = np.arange(10, 100, 10)
a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print('1st element', a1[0])

1st element 10


In [ ]:
print('5th element', a1[4])

5th element 50


In [ ]:
print('last element', a1[-1])

last element 90


In [ ]:
print('Second to Eight elements', a1[1:8])

Second to Eight elements [20 30 40 50 60 70 80]


In [ ]:
print('2nd element from reverse', a1[-2])

2nd element from reverse 80


In [ ]:
print('last 5 elements', a1[:5])

last 5 elements [10 20 30 40 50]


In [ ]:
print('last 5 elements', a1[-5:])

last 5 elements [50 60 70 80 90]


In [ ]:
print('alternate element', a1[::2])

alternate element [10 30 50 70 90]


In [ ]:
a12 = np.arange(1, 101)
a12 = np.reshape(a12, (10, 10))
a12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
print('Element at 1st row 1st column', a12[0][0])

Element at 1st row 1st column 1


In [ ]:
print('Element at 1st row 5th column', a12[0, 4])

Element at 1st row 5th column 5


In [ ]:
print('Element at 2nd row', a12[1])

Element at 2nd row [11 12 13 14 15 16 17 18 19 20]


In [ ]:
print('Element at 1st column', a12[:, 0])

Element at 1st column [ 1 11 21 31 41 51 61 71 81 91]


In [ ]:
a1 = np.array([10, 5, 20, 8, 7, 4, 5])
a1

array([10,  5, 20,  8,  7,  4,  5])

In [ ]:
np.unique(a1)

array([ 4,  5,  7,  8, 10, 20])

In [ ]:
np.sort(a1)

array([ 4,  5,  5,  7,  8, 10, 20])

In [ ]:
np.sort(a1)[::-1]

array([20, 10,  8,  7,  5,  5,  4])

In [ ]:
np.min(a1)

4

In [ ]:
np.max(a1)

20

In [ ]:
np.argmax(a1)

2

In [ ]:
np.argmin(a1)

5

In [ ]:
print('Mean', np.mean(a1))
print('Median', np.median(a1))
print('Std', np.std(a1))
print('Variance', np.var(a1))

Mean 8.428571428571429
Median 7.0
Std 5.0950155714648595
Variance 25.959183673469386


In [ ]:
sh = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sh

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sh = np.array([2, 4, 5, 3, 6])
m = np.array([50, 70, 80, 55, 80])
print('cov')
print(np.cov(sh, m))

cov
[[  2.5   21.25]
 [ 21.25 195.  ]]


In [ ]:
sh = np.array([2, 4, 5, 3, 6])
m = np.array([50, 70, 80, 55, 80])
print('cov')
print(np.corrcoef(sh, m))

cov
[[1.         0.96243548]
 [0.96243548 1.        ]]


In [ ]:
sh = np.array([2, 4, 5, 3, 6])
m = np.array([50, 70, 80, 55, 80])
print('cov')
print(np.corrcoef(sh))

cov
1.0


In [ ]:
sh = np.array([2, 4, 5, 3, 6])
m = np.array([50, 20, 60, 25, 50])
print('cov')
print(np.corrcoef(sh, m))

cov
[[1.         0.31687511]
 [0.31687511 1.        ]]


In [ ]:
np.save('a12_file',a12)

In [ ]:
a13 = np.load('a12_file.npy')
a13

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/Diwali Sales Data.csv', encoding= 'unicode_escape')

In [ ]:
df.shape

(11251, 15)

In [ ]:
df.head()

User_ID  Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
0  1002903  Sanskriti  P00125942      F     26-35   28               0   
1  1000732     Kartik  P00110942      F     26-35   35               1   
2  1001990      Bindu  P00118542      F     26-35   35               1   
3  1001425     Sudevi  P00237842      M      0-17   16               0   
4  1000588       Joni  P00057942      M     26-35   28               1   

            State      Zone       Occupation Product_Category  Orders  \
0     Maharashtra   Western       Healthcare             Auto       1   
1  Andhra Pradesh  Southern             Govt             Auto       3   
2   Uttar Pradesh   Central       Automobile             Auto       3   
3       Karnataka  Southern     Construction             Auto       2   
4         Gujarat   Western  Food Processing             Auto       2   

    Amount  Status  unnamed1  
0  23952.0     NaN       NaN  
1  23934.0     NaN       NaN  
2  23924.0     NaN       NaN  
3  23912.0     NaN       NaN  
4  23877.0     NaN       NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   User_ID           11251 non-null  int64  
 1   Cust_name         11251 non-null  object 
 2   Product_ID        11251 non-null  object 
 3   Gender            11251 non-null  object 
 4   Age Group         11251 non-null  object 
 5   Age               11251 non-null  int64  
 6   Marital_Status    11251 non-null  int64  
 7   State             11251 non-null  object 
 8   Zone              11251 non-null  object 
 9   Occupation        11251 non-null  object 
 10  Product_Category  11251 non-null  object 
 11  Orders            11251 non-null  int64  
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB


In [ ]:
print(df.columns)

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount', 'Status', 'unnamed1'],
      dtype='object')


In [ ]:
# Check if the columns 'status' and 'unnamed1' exist before dropping them
if 'status' in df.columns and 'unnamed1' in df.columns:
    df.drop(['status','unnamed1'], axis=1, inplace=True)
else:
    print("Column 'status' or 'unnamed1' not found in DataFrame.")
    # Check the actual column names using: print(df.columns)
    # and update the drop command with the correct names if needed
df.head()

Column 'status' or 'unnamed1' not found in DataFrame.


User_ID  Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
0  1002903  Sanskriti  P00125942      F     26-35   28               0   
1  1000732     Kartik  P00110942      F     26-35   35               1   
2  1001990      Bindu  P00118542      F     26-35   35               1   
3  1001425     Sudevi  P00237842      M      0-17   16               0   
4  1000588       Joni  P00057942      M     26-35   28               1   

            State      Zone       Occupation Product_Category  Orders  \
0     Maharashtra   Western       Healthcare             Auto       1   
1  Andhra Pradesh  Southern             Govt             Auto       3   
2   Uttar Pradesh   Central       Automobile             Auto       3   
3       Karnataka  Southern     Construction             Auto       2   
4         Gujarat   Western  Food Processing             Auto       2   

    Amount  Status  unnamed1  
0  23952.0     NaN       NaN  
1  23934.0     NaN       NaN  
2  23924.0     NaN       NaN  
3  23912.0     NaN       NaN  
4  23877.0     NaN       NaN

In [ ]:
df.isnull().sum()

User_ID                 0
Cust_name               0
Product_ID              0
Gender                  0
Age Group               0
Age                     0
Marital_Status          0
State                   0
Zone                    0
Occupation              0
Product_Category        0
Orders                  0
Amount                 12
Status              11251
unnamed1            11251
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df['Amount'] = df['Amount'].astype('int')

In [ ]:
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount', 'Status', 'unnamed1'],
      dtype='object')

In [ ]:
df.rename(columns = {'Marital_Status':'Shaadi'})
df.head()

Empty DataFrame
Columns: [User_ID, Cust_name, Product_ID, Gender, Age Group, Age, Marital_Status, State, Zone, Occupation, Product_Category, Orders, Amount, Status, unnamed1]
Index: []

In [ ]:
df[['Age', 'Orders', 'Amount']].describe()

Age  Orders  Amount
count  0.0     0.0     0.0
mean   NaN     NaN     NaN
std    NaN     NaN     NaN
min    NaN     NaN     NaN
25%    NaN     NaN     NaN
50%    NaN     NaN     NaN
75%    NaN     NaN     NaN
max    NaN     NaN     NaN

In [ ]:
age = [20, 19, 20, 18, 21, 22]
m_age = st.mean(age)
print('Mean Age: ', m_age)

Mean Age:  20


In [ ]:
age = [20, 19, 20, 18, 21, 22]
m_age = st.median(age)
print('Median Age: ', m_age)

Median Age:  20.0


In [ ]:
s_cores = [1, 2, 3, 1, 2, 2, 2, 4, 3, 3, 1]
md_s_cores = st.mode(s_cores)
print('Mode of Score: ', md_s_cores)

Mode of Score:  2


In [ ]:
age = [20, 19, 20, 18, 21, 22, 20]
r_age = max(age) - min(age)
print('Range of Age: ', r_age)

Range of Age:  4


In [ ]:
age = [20, 19, 20, 18, 21, 22, 20]
v_age = st.variance(age)
print('Variance of Age: ', v_age)

Variance of Age:  1.6666666666666667
